# Generated by Django 4.2.18 on 2026-01-14 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0020_chat_summary_last_message_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'NEW'), ('in_progress', 'IN_PROGRESS'), ('closed', 'CLOSED')], default='new', max_length=20)),
                ('created_at_ts', models.DateTimeField(auto_now_add=True)),
                ('in_progress_ts', models.DateTimeField(blank=True, null=True)),
                ('closed_at_ts', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_assistance_requests', to='chats.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_assistance_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legal Assistance Request',
                'verbose_name_plural': 'Legal Assistance Requests',
                'ordering': ['-created_at_ts'],
            },
        ),
    ]
