# Generated by Django 4.2.18 on 2026-01-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalassistancerequest',
            name='in_charge',
            field=models.CharField(blank=True, help_text='Name of the admin/person in charge of this request. Required when moving to in_progress or closed.', max_length=255, null=True),
        ),
    ]
