# Generated by Django 4.2.18 on 2026-01-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0002_legalassistancerequest_in_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalassistancerequest',
            name='in_charge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
