# Generated by Django 4.2.18 on 2025-01-21 06:05

from django.db import migrations, models
import django.db.models.deletion
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message'),
    ]

    operations = [
        VectorExtension(),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chat'),
        ),
    ]
