# Generated by Django 4.2.18 on 2025-01-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_messagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefile',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
