# Generated by Django 4.2.18 on 2025-02-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_messagefile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefile',
            name='file',
            field=models.FileField(serialize=False, upload_to='uploads/'),
        ),
    ]
