# Generated by Django 4.2.18 on 2025-03-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_messagefile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='jurisdiction',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
