# Generated by Django 4.2.18 on 2025-03-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_messagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='used_query',
            field=models.TextField(null=True),
        ),
    ]
