# Generated by Django 4.2.18 on 2025-07-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_message_used_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='jurisdiction',
        ),
    ]
