# Generated by Django 4.2.18 on 2025-07-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_remove_chat_jurisdiction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='show_translation_disclaimer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='translation_disclaimer_language',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
