# Generated by Django 4.2.18 on 2025-07-26 12:42

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_message_language_message_show_translation_disclaimer_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='messagelog',
            managers=[
                ('logs_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
