# Generated by Django 4.2.18 on 2025-11-12 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0014_alter_message_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageStepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('time_sec', models.BigIntegerField(blank=True, null=True)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messageStepLogs', to='chats.message')),
            ],
            managers=[
                ('logs_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
