# Generated by Django 4.2.18 on 2025-11-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0015_messagesteplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesteplog',
            name='step_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
