# Generated by Django 4.2.18 on 2025-11-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0016_messagesteplog_step_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='messagesteplog',
            managers=[
            ],
        ),
    ]
