# Generated by Django 4.2.18 on 2025-11-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0017_alter_messagesteplog_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesteplog',
            name='time_sec',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
