# Generated by Django 4.2.18 on 2026-02-28 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0021_message_metadata_attachments_pending_intent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pendingdocintent',
            new_name='chats_pendi_tenant__6e0d3e_idx',
            old_name='chats_pendi_tenant__status_idx',
        ),
    ]
