# Generated by Django 4.2.18 on 2026-04-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0023_chatexport'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatexport',
            new_name='chats_chat__owner_i_ef25db_idx',
            old_name='chats_export_owner_created_idx',
        ),
    ]
