# Generated by Django 4.2.18 on 2025-03-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_company_name_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jurisdiction',
            field=models.JSONField(default=list, null=True),
        ),
    ]
