# Generated by Django 4.2.18 on 2025-07-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_jurisdiction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jurisdiction',
        ),
    ]
