# Generated by Django 4.2.18 on 2026-01-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='legal_company_referrer',
            field=models.CharField(blank=True, choices=[('jp_legal', 'JP_LEGAL')], help_text='Legal company that referred this user', max_length=50, null=True),
        ),
    ]
