# Generated by Django 4.2.18 on 2026-04-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_legal_company_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('fr', 'French'), ('hi', 'Hindi'), ('ur', 'Urdu')], default='ar', max_length=10),
        ),
    ]
