# Generated by Django 4.2.18 on 2025-01-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reference_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedocument',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referencedocument',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='referencedocument',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('processed', 'processed'),
                                            ('failed', 'Failed')], default='new', max_length=20),
        ),
    ]
