# Generated by Django 4.2.18 on 2025-01-21 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_documents', '0002_referencedocument_text_alter_referencedocument_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDocumentPart',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('reference_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_documents.referencedocument')),
            ],
        ),
    ]
