# Generated by Django 4.2.18 on 2025-01-21 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_documents', '0003_referencedocumentpart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencedocumentpart',
            name='reference_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='reference_documents.referencedocument'),
        ),
    ]
