# Generated by Django 4.2.18 on 2025-01-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_documents', '0004_alter_referencedocumentpart_reference_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencedocument',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
