# Generated by Django 4.2.18 on 2025-01-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_documents', '0005_alter_referencedocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencedocument',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
