# Generated by Django 4.2.18 on 2025-02-23 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference_documents', '0006_alter_referencedocument_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedocument',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reference_documents', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='referencedocument',
            name='jurisdiction',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='referencedocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
