# Generated by Django 4.2.18 on 2025-07-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_documents', '0007_referencedocument_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencedocument',
            name='jurisdiction',
        ),
        migrations.AddField(
            model_name='referencedocument',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
