# Generated by Django 4.2.18 on 2025-07-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_documents', '0008_remove_referencedocument_jurisdiction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedocument',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
