# Generated by Django 4.2.18 on 2025-07-26 17:35

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('reference_documents', '0009_referencedocument_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedocument',
            name='description_embedding',
            field=pgvector.django.VectorField(null=True),
        ),
    ]
