# Generated by Django 4.2.18 on 2025-08-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_documents', '0010_referencedocument_description_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencedocument',
            name='file_name',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
