# Generated by Django 4.2.18 on 2025-08-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_documents', '0011_alter_referencedocument_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencedocument',
            name='name',
            field=models.CharField(max_length=350),
        ),
    ]
