# Generated by Django 4.2.18 on 2025-11-09 12:46

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('reference_documents', '0012_alter_referencedocument_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencedocument',
            name='description_embedding',
            field=pgvector.django.halfvec.HalfVectorField(dimensions=3072, null=True),
        ),
        migrations.AddIndex(
            model_name='referencedocument',
            index=pgvector.django.HnswIndex(ef_construction=256, fields=['description_embedding'], m=48, name='description_embedding_hnsw_idx', opclasses=['halfvec_cosine_ops']),
        ),
    ]
