# Generated by Django 4.2.18 on 2025-11-09 14:42

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ('reference_documents', '0013_alter_referencedocument_description_embedding_and_more'),
    ]

    operations = [
        RunSQL(
            sql="""
                    ALTER TABLE langchain_pg_embedding ALTER COLUMN embedding TYPE halfvec(3072);
                    """,
        ),
    ]
