# Generated by Django 4.2.18 on 2025-11-10 01:40

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ('reference_documents', '0014_auto_20251109_1442'),
    ]

    operations = [
        RunSQL(
            sql="""
                    CREATE INDEX idx_hnsw_langchain_pg_embedding ON langchain_pg_embedding USING hnsw (embedding halfvec_cosine_ops)
        WITH (m = 48, ef_construction = 256);
        """,
            reverse_sql="""
                    DROP INDEX IF EXISTS idx_hnsw_langchain_pg_embedding;        
                    """
        )
    ]
