# Generated by Django 4.2.18 on 2025-11-10 02:25

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ('reference_documents', '0015_auto_20251110_0140'),
    ]

    operations = [
        RunSQL(sql="""
    CREATE INDEX IF NOT EXISTS idx_cmetadata_referencedocumentid_embedding
    ON langchain_pg_embedding 
    USING btree 
    (((cmetadata ->> 'reference_document_id')::bigint));
        """,
               reverse_sql="DROP INDEX idx_cmetadata_referencedocumentid_embedding"
               )
    ]
