# Generated by Django 4.2.18 on 2025-11-10 14:40

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ('reference_documents', '0016_auto_20251110_0225'),
    ]

    operations = [
        RunSQL(
            sql="TRUNCATE TABLE langchain_pg_embedding RESTART IDENTITY CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        RunSQL(
            sql="DROP INDEX IF EXISTS idx_hnsw_langchain_pg_embedding;"
        ),
        RunSQL(
            sql="ALTER TABLE langchain_pg_embedding ALTER COLUMN embedding TYPE vector(1536);"
        ),
        RunSQL(
            sql="""
                CREATE INDEX idx_hnsw_langchain_pg_embedding ON langchain_pg_embedding USING hnsw (embedding vector_cosine_ops)
    WITH (m = 12, ef_construction = 120);
    """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_hnsw_langchain_pg_embedding;        
                """
        ),
        RunSQL(sql="""
    CREATE INDEX IF NOT EXISTS idx_cmetadata_referencedocumentid_embedding
    ON langchain_pg_embedding 
    USING btree 
    (((cmetadata ->> 'reference_document_id')::bigint));
        """,
               reverse_sql="DROP INDEX idx_cmetadata_referencedocumentid_embedding"
               )
    ]
