# Generated by Django 4.2.18 on 2025-11-10 15:05

from django.db import migrations
import pgvector.django.indexes
import pgvector.django.vector
from django.db.migrations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ('reference_documents', '0017_auto_20251110_1440'),
    ]

    operations = [
        RunSQL(
            "UPDATE reference_documents_referencedocument SET description_embedding = NULL;"
        ),
        migrations.RemoveIndex(
            model_name='referencedocument',
            name='description_embedding_hnsw_idx',
        ),
        migrations.AlterField(
            model_name='referencedocument',
            name='description_embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, null=True),
        ),
        migrations.AddIndex(
            model_name='referencedocument',
            index=pgvector.django.indexes.HnswIndex(ef_construction=120, fields=['description_embedding'], m=12, name='description_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
