# Generated by Django 4.2.18 on 2026-03-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_documents', '0018_remove_referencedocument_description_embedding_hnsw_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RagSourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid5', models.UUIDField(unique=True)),
                ('title', models.CharField(max_length=512)),
                ('s3_bucket', models.CharField(blank=True, max_length=255, null=True)),
                ('s3_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('pulled_at', models.DateTimeField(blank=True, null=True)),
                ('is_extracted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
