# Generated by Django 4.2.18 on 2026-02-28 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='file',
            new_name='uploads_fil_tenant__f483ac_idx',
            old_name='uploads_file_tenant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='file',
            new_name='uploads_fil_tenant__5a53a2_idx',
            old_name='uploads_file_tenant_sha256_idx',
        ),
        migrations.RenameIndex(
            model_name='fileextraction',
            new_name='uploads_fil_file_id_5b85d9_idx',
            old_name='uploads_fileextraction_file_status_idx',
        ),
        migrations.RenameIndex(
            model_name='filesummary',
            new_name='uploads_fil_tenant__0dc9c6_idx',
            old_name='uploads_filesummary_tenant_file_idx',
        ),
    ]
