# Generated by Django 4.2.18 on 2025-10-12 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoyasarInvoice',
            fields=[
                ('internal_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id', models.UUIDField(blank=True, null=True, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('SAR', 'Saudi Riyal'), ('USD', 'US Dollar')], default='SAR', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('amount_format', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('back_url', models.URLField(blank=True, null=True)),
                ('success_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='MoyasarPaymentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('type', models.CharField(choices=[('token', 'Token'), ('creditcard', 'Credit Card')], max_length=50)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('number', models.CharField(blank=True, max_length=30, null=True)),
                ('gateway_id', models.CharField(blank=True, max_length=120, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=120, null=True)),
                ('token', models.CharField(blank=True, max_length=120, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('transaction_url', models.URLField(blank=True, null=True)),
                ('response_code', models.CharField(blank=True, max_length=50, null=True)),
                ('authorization_code', models.CharField(blank=True, max_length=50, null=True)),
                ('issuer_name', models.CharField(blank=True, max_length=120, null=True)),
                ('issuer_country', models.CharField(blank=True, max_length=50, null=True)),
                ('issuer_card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('issuer_card_category', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoyasarWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('payment_paid', 'Payment Paid'), ('payment_failed', 'Payment Failed'), ('payment_authorized', 'Payment Authorized'), ('payment_captured', 'Payment Captured'), ('payment_refunded', 'Payment Refunded'), ('payment_voided', 'Payment Voided')], max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('live', models.BooleanField(default=False)),
                ('event_created_at', models.DateTimeField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='MoyasarPayment',
            fields=[
                ('internal_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id', models.UUIDField(blank=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('paid', 'Paid'), ('failed', 'Failed'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('refunded', 'Refunded'), ('voided', 'Voided'), ('verified', 'Verified')], max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('fee', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(choices=[('SAR', 'Saudi Riyal'), ('USD', 'US Dollar')], default='SAR', max_length=10)),
                ('refunded', models.PositiveIntegerField(default=0)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('captured', models.PositiveIntegerField(default=0)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_format', models.CharField(blank=True, max_length=50, null=True)),
                ('fee_format', models.CharField(blank=True, max_length=50, null=True)),
                ('refunded_format', models.CharField(blank=True, max_length=50, null=True)),
                ('captured_format', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payment.moyasarinvoice')),
                ('source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payment.moyasarpaymentsource')),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(help_text='Payment token for reuse', max_length=120)),
                ('token_type', models.CharField(choices=[('token', 'Token'), ('creditcard', 'Credit Card')], default='token', help_text='Type of the payment token', max_length=50)),
                ('is_default', models.BooleanField(default=False, help_text="Whether this is the user's default payment method")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment source is active')),
                ('nickname', models.CharField(blank=True, help_text='User-friendly name for this payment method', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='payment.moyasarpaymentsource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='payment_use_user_id_530414_idx'), models.Index(fields=['user', 'is_default'], name='payment_use_user_id_3bd197_idx')],
                'unique_together': {('user', 'token')},
            },
        ),
    ]
