# Generated by Django 4.2.18 on 2025-10-13 21:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_usersubscription_unique_active_subscription_per_user'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentUserSubscription',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_link', to='payment.moyasarpayment')),
                ('user_subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_link', to='subscription.usersubscription')),
            ],
        ),
    ]
