"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import json
import os
import sys
from datetime import timedelta
from pathlib import Path

import environ
from langchain_openai import OpenAIEmbeddings
from langchain_postgres import PGVector
from langchain_postgres.vectorstores import DistanceStrategy

from src.common.utils import get_db_url

# Detect if we're running tests
# Check if 'test' command is in sys.argv (for 'python manage.py test')
# or if pytest is being used, or if DJANGO_TESTING env var is set
TESTING = (
    (len(sys.argv) > 1 and sys.argv[1] == 'test') or  # python manage.py test
    'pytest' in sys.argv[0] or  # pytest runner
    'test' in sys.argv or  # fallback: any 'test' in args
    os.environ.get('DJANGO_TESTING') == '1'  # explicit env var
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Default value is only for testing - production must set SECRET_KEY environment variable
SECRET_KEY = env("SECRET_KEY", default="django-insecure-test-key-change-in-production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', False)
# Default value is only for testing - production must set ASPOSE_LICENSE_PATH environment variable
ASPOSE_LICENSE_PATH = env('ASPOSE_LICENSE_PATH', default='')

ALLOWED_HOSTS = [
    '*'
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:4200',
    'http://localhost:4201',
    'http://localhost:4002',
    'http://127.0.0.1:4002',
    'https://admin.nizami.xob-webservices.com',
    'https://nizami.xob-webservices.com',

    'https://www.admin.app.nizami.ai',
    'https://www.app.nizami.ai',
    'https://admin.app.nizami.ai',
    'https://app.nizami.ai',
    'http://localhost:4202',
    'https://main.d15yqles4zx6o7.amplifyapp.com',
    'https://www.nizami.ai',
]

# CORS additional settings
CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'allauth',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_extensions',
    'django_q',
    'storages',

    'src.common',
    'src.authentication',
    'src.users',
    'src.reference_documents',
    'src.chats',
    'src.dashboard',
    'src.prompts',
    
    'src.plan',
    'src.payment',
    'src.subscription',
    'src.ledger',
    'src.gibberish',
    'src.user_requests',
    'src.uploads',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware must be early
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'src.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'src.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Use SQLite for testing, PostgreSQL for production/development
if TESTING:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        },
        'logs': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST'),
            'PORT': env('DB_PORT'),
            'CONN_MAX_AGE': 600,
            'OPTIONS': {
                'options': '-c hnsw.ef_search=32',
            }
        },
        'logs': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST'),
            'PORT': env('DB_PORT'),
            'CONN_MAX_AGE': 600,
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# S3 / object storage configuration for MEDIA files (STATIC remains on disk)
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', default=None)
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', default=None)
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME', default=None)
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME', default=None)
AWS_S3_ENDPOINT_URL = env('AWS_S3_ENDPOINT_URL', default=None)
USE_LOCALSTACK_S3 = env.bool('USE_LOCALSTACK_S3', default=False)

# STORAGES (Django 4.2+); replaces deprecated DEFAULT_FILE_STORAGE
STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage'
        if (not TESTING and AWS_STORAGE_BUCKET_NAME)
        else 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}
if not TESTING and AWS_STORAGE_BUCKET_NAME:
    # Path-style for LocalStack/custom endpoint; omit for real AWS (virtual-hosted default).
    if USE_LOCALSTACK_S3 or AWS_S3_ENDPOINT_URL:
        AWS_S3_ADDRESSING_STYLE = 'path'
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_DEFAULT_ACL = None
    AWS_S3_VERIFY = not USE_LOCALSTACK_S3

    if AWS_S3_ENDPOINT_URL:
        AWS_S3_CUSTOM_DOMAIN = None

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],

    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework_datatables.renderers.DatatablesRenderer',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework_datatables.filters.DatatablesFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework_datatables.pagination.DatatablesPageNumberPagination',
    'PAGE_SIZE': 50,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=0),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
if TESTING:
    # Use console backend for testing
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_HOST = 'localhost'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = False
    EMAIL_HOST_USER = ''
    EMAIL_HOST_PASSWORD = ''
    EMAIL_FROM_ADDRESS = 'test@example.com'
else:
    EMAIL_HOST = env('EMAIL_HOST', default='smtp.mailgun.org')
    EMAIL_PORT = env.int('EMAIL_PORT', default=587)
    EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
    EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='hello@nizami.ai')
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
    EMAIL_FROM_ADDRESS = env('EMAIL_FROM_ADDRESS', default='hello@nizami.ai')
# MAIL_MAILER=smtp


AUTH_USER_MODEL = 'users.User'

APPEND_SLASH = True

FRONTEND_DOMAIN = env('FRONTEND_DOMAIN', default='http://localhost:4201') if not TESTING else 'http://localhost:4201'
FRONTEND_RESET_PASSWORD_TEMPLATE = env('FRONTEND_RESET_PASSWORD_TEMPLATE', default='/reset-password') if not TESTING else '/reset-password'

Q_CLUSTER = {
    'name': 'DjangoQ',
    'workers': 1,  # Number of worker processes
    'recycle': 50,  # Restart worker after processing 50 tasks
    'timeout': 60 * 60 * 2,  # Task timeout in seconds
    'retry': 60 * 60 * 2,
    'compress': True,  # Compress task payloads
    'save_limit': 50,  # Keep the last 50 task results in the database
    'queue_limit': 50,  # Limit the size of the queue
    'cpu_affinity': 1,  # Number of cores to use
    'orm': 'default',  # Use the default database as the broker
}

# When the user sends a message with attachments, we poll for extraction to complete
# before returning a full answer. Increase this if the queue is often busy (e.g. 60–120 seconds).
ATTACHMENT_EXTRACTION_WAIT_TIMEOUT_SEC = env.int('ATTACHMENT_EXTRACTION_WAIT_TIMEOUT_SEC', default=60)
ATTACHMENT_EXTRACTION_POLL_INTERVAL_SEC = env.float('ATTACHMENT_EXTRACTION_POLL_INTERVAL_SEC', default=0.5)

# Use OpenAI LLM to extract or refine document text after library extraction (and for PDFs with no text, use vision).
USE_OPENAI_FOR_EXTRACTION = env.bool('USE_OPENAI_FOR_EXTRACTION', default=True)

OPENAI_API_KEY = env('OPENAI_API_KEY', default='') if not TESTING else ''

# Initialize embeddings and vectorstore only if not testing and OPENAI_API_KEY is set
try:
    embeddings = OpenAIEmbeddings(model='text-embedding-3-large', dimensions=1536, openai_api_key=OPENAI_API_KEY)
    vectorstore = PGVector(
        collection_name="reference_document_parts",
        embeddings=embeddings,
        connection=get_db_url(),
        distance_strategy=DistanceStrategy.COSINE,
        create_extension=False,
    )
except Exception as ex:
    print(json.dumps(dict(msg='PGVector init failed', error=str(ex)), default=str))
    embeddings = None
    vectorstore = None

CSRF_TRUSTED_ORIGINS = [
    'https://api.nizami.xob-webservices.com',
    'https://admin.nizami.xob-webservices.com',
    'https://nizami.xob-webservices.com',
    'https://api.app.nizami.ai',
    'https://admin.app.nizami.ai',
    'https://app.nizami.ai',
    'https://www.admin.app.nizami.ai',
    'https://www.app.nizami.ai',
    'https://nizami.ai',
    'http://localhost:4202',
    'https://main.d15yqles4zx6o7.amplifyapp.com/',
    'https://www.nizami.ai',
]

MOYASAR_URL = env('MOYASAR_URL', default='') if not TESTING else ''
MOYASAR_SECRET_KEY = env('MOYASAR_SECRET_KEY', default='') if not TESTING else ''
MOYASAR_WEBHOOK_SECRET_KEY = env('MOYASAR_WEBHOOK_SECRET_KEY', default='') if not TESTING else ''

RAG_S3_BUCKET = env('RAG_S3_BUCKET', default='')
RAG_S3_PREFIX = env('RAG_S3_PREFIX', default='')
RAG_S3_REGION = env('RAG_S3_REGION', default=env('AWS_DEFAULT_REGION', default=''))

# "old" = use langchain_pg_embedding (ReferenceDocument pipeline)
# "new" = use RagSourceDocumentChunk table (S3 RAG pipeline)
RAG_SOURCE = env('RAG_SOURCE', default='new')

# ---------------------------------------------------------------------------
# Web Search Configuration
# ---------------------------------------------------------------------------
# Set WEB_SEARCH_ENABLED=true to enable live web search alongside the internal
# RAG pipeline. Both run in parallel; if web search fails or times out the
# answer falls back to RAG-only automatically.
#
# Supported providers (WEB_SEARCH_PROVIDER):
#   "duckduckgo" — free, no API key required (default)
#   "tavily"     — paid, better RAG-optimised results; requires TAVILY_API_KEY
#
# Tuning:
#   WEB_SEARCH_TIMEOUT_SEC  — hard deadline for the web search branch (default 10)
#   WEB_SEARCH_NUM_RESULTS  — how many web results to pass to the LLM (default 5)
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Reranking Configuration
# ---------------------------------------------------------------------------
# Set ENABLE_RERANKING=false to skip the Flashrank cross-encoder reranking
# step and pass the raw top-k vector results directly to the LLM.
# Disabling this can improve answer quality when the reranker is filtering out
# relevant documents, at the cost of less precise ranking.
# ---------------------------------------------------------------------------
ENABLE_RERANKING = env.bool('ENABLE_RERANKING', default=True)

WEB_SEARCH_ENABLED = env.bool('WEB_SEARCH_ENABLED', default=False)
WEB_SEARCH_PROVIDER = env('WEB_SEARCH_PROVIDER', default='duckduckgo')
TAVILY_API_KEY = env('TAVILY_API_KEY', default='') if not TESTING else ''
WEB_SEARCH_TIMEOUT_SEC = env.float('WEB_SEARCH_TIMEOUT_SEC', default=10.0)
WEB_SEARCH_NUM_RESULTS = env.int('WEB_SEARCH_NUM_RESULTS', default=5)