# Generated by Django 4.2.18 on 2025-10-10 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('BASIC', 'Basic'), ('PLUS', 'Plus'), ('PREMIUM', 'Premium')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_cents', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('interval_unit', models.CharField(blank=True, choices=[('MONTH', 'Month'), ('YEAR', 'Year')], max_length=20, null=True)),
                ('interval_count', models.IntegerField(blank=True, default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('credit_amount', models.IntegerField(blank=True, null=True)),
                ('credit_type', models.CharField(choices=[('MESSAGES', 'Messages')], max_length=50)),
                ('is_unlimited', models.BooleanField(default=False)),
                ('rollover_allowed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plans',
            },
        ),
    ]
