# Generated by Django 4.2.18 on 2025-10-10 20:09

from django.db import migrations

def create_initial_plans(apps, schema_editor):
    """Create initial plans: Free, Paid, and Premium"""
    Plan = apps.get_model('plan', 'Plan')
    
    # Free Plan - 10 credits only (no recurring billing)
    Plan.objects.create(
        name='Free Plan',
        tier='BASIC',
        description='Free plan with 10 message credits to get started',
        price_cents=0,
        currency='USD',
        interval_unit='MONTH', #Need value here for dynamic client subscription record upon registering.
        interval_count=1,
        is_active=True,
        credit_amount=10,
        credit_type='MESSAGES',
        is_unlimited=False,
        rollover_allowed=False
    )
    
    # Paid Plan - $50 for 40 questions per month
    Plan.objects.create(
        name='Plus Plan',
        tier='PLUS',
        description='Plus plan with 40 message credits per month',
        price_cents=5000,  # $50.00
        currency='USD',
        interval_unit='MONTH',
        interval_count=1,
        is_active=True,
        credit_amount=40,
        credit_type='MESSAGES',
        is_unlimited=False,
        rollover_allowed=False
    )
    
    # Premium Plans - Monthly and Yearly
    Plan.objects.create(
        name='Premium Plan',
        tier='PREMIUM',
        description='Premium plan (monthly) with unlimited message credits',
        price_cents=10000,  # $100.00 monthly
        currency='USD',
        interval_unit='MONTH',
        interval_count=1,
        is_active=True,
        credit_amount=None,
        credit_type='MESSAGES',
        is_unlimited=True,
        rollover_allowed=False
    )


def remove_initial_plans(apps, schema_editor):
    """Remove initial plans if migration is reversed"""
    Plan = apps.get_model('plan', 'Plan')
    Plan.objects.filter(
        name__in=['Free Plan', 'Plus Plan', 'Premium Plan']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_plans, remove_initial_plans),
    ]
