# Generated by Django 4.2.18 on 2025-10-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20251010_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
