# Generated by Django 4.2.18 on 2025-10-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_plan_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='credit_type',
            field=models.CharField(blank=True, choices=[('MESSAGES', 'Messages')], max_length=50, null=True),
        ),
    ]
