# Generated by Django 4.2.18 on 2025-10-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_alter_plan_credit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='tier',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PLUS', 'Plus'), ('PREMIUM_MONTHLY', 'Premium-Monthly'), ('PREMIUM_YEARLY', 'Premium-Yearly')], max_length=50),
        ),
    ]
