# Generated by Django 4.2.18 on 2025-10-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_alter_plan_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='tier',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PLUS', 'Plus'), ('PREMIUM', 'Premium')], max_length=50),
        ),
    ]
