# Generated by Django 4.2.18 on 2025-10-13 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0002_usersubscription_unique_active_subscription_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='credit_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='credit_type',
            field=models.CharField(choices=[('MESSAGES', 'Messages')], default='MESSAGES', max_length=50),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
