# استخدم صورة Python
FROM python:3.9

# تعيين مجلد العمل
WORKDIR /app

# نسخ متطلبات المشروع
COPY requirements.txt .

# تثبيت المتطلبات
RUN pip install -r requirements.txt

# نسخ باقي الملفات
COPY . .

# فتح البورت الخاص بـ Django
EXPOSE 8000

# تشغيل الخادم
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
